[http]
  [http.routers]
    [http.routers.red]
      entryPoints = ["http"]
      rule = "Host(`traefik.devopsua.tk`) && PathPrefix(`/red`)"
      service = "nginx-red"
    [http.routers.green]
      entryPoints = ["http"]
      rule = "Host(`traefik.devopsua.tk`) && PathPrefix(`/green`)"
      service = "nginx-green"


[http.services]
  [http.services.nginx-red.loadBalancer]

    [[http.services.nginx-red.loadBalancer.servers]]
      url = "http://10.96.0.1:8080/"
    [[http.services.nginx-red.loadBalancer.servers]]
      url = "http://10.96.0.2:8080/"

  [http.services.nginx-green.loadBalancer]

    [[http.services.nginx-green.loadBalancer.servers]]
      url = "http://10.96.0.11:8080/"
    [[http.services.nginx-green.loadBalancer.servers]]
      url = "http://10.96.0.12:8080/"