apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-webacademy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitlab.devopsua.tk/3005/staging-argocd-apps.git
    targetRevision: HEAD
    path: webacad
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: app-of-apps-apps
#  namespace: argocd
#spec:
#  project: default
#  source:
#    repoURL: https://gitlab.devopsua.tk/1409/infra.git
#    targetRevision: HEAD
#    path: kubernetes/staging/apps
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: argocd
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: app-of-apps-logging
#  namespace: argocd
#spec:
#  project: default
#  source:
#    repoURL: https://gitlab.devopsua.tk/1803/infra.git
#    targetRevision: HEAD
#    path: kubernetes/poc/logging
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: argocd
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true