image:
  tag: ""
logs:
  general:
    level: INFO
  access:
    # To enable access logs
    enabled: true
resources:
   requests:
     cpu: "100m"
     memory: "50Mi"
   limits:
     memory: "150Mi"
ports:
  traefik:
    expose: true
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
#ingressClass:
#  # true is not unit-testable yet, pending https://github.com/rancher/helm-unittest/pull/12
#  enabled: true
ingressRoute:
  dashboard:
    enabled: true

service:
  enabled: true
  type: NodePort